url: https://sensible-prin.github.io
baseurl: /

# Site settings
title: SENSIBLE
email: anna.bernasconi@polimi.it
description: ""


# Team names, titles and social links
people:
- name: Dr. Anna Bernasconi
  pic: 1
  position: Research Assistant (Politecnico di Milano)

- name: Prof. Matteo Chiara
  pic: 2
  position: Associate Professor (Università degli Studi di Milano)

- name: Prof. Stefano Ceri
  pic: 3
  position: Full Professor (Politecnico di Milano)

- name: Tommaso Alfonsi
  pic: 4
  position: Postdoc Researcher (Politecnico di Milano)

- name: Prof. Alessandro Campi
  pic: 5
  position: Research Assistant (Politecnico di Milano)

- name: Luca Cassenti
  pic: 6
  position: Master Student (Politecnico di Milano)

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
